export const DOWNLOADING_ERROR = 'DOWNLOADING_ERROR';
export const LOADING = 'LOADING';
export const RECEIVE_FILM_DETAILS = 'RECEIVE_FILM_DETAILS';
export const RECEIVE_FILMS = 'RECEIVE_FILMS';
export const SET_SEARCH_TYPE = 'SET_SEARCH_TYPE';
export const SET_SORT_TYPE = 'SET_SORT_TYPE';
export const CLEAR_INPUT_VALUE = 'CLEAR_INPUT_VALUE';
export const SET_INPUT_VALUE = 'SET_INPUT_VALUE';
